import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <a href='/'> Home</a>
          <a href='/events'> Events</a>
          <a href='/about-us'> About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        <div>
          <h2> Events in London</h2>
          <p></p>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
